version: '3.8'

services:
  youtube-streaming-bot:
    build: .
    container_name: youtube_streaming_bot
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
      - ./static/uploads:/app/static/uploads
      - /dev/shm:/dev/shm  # For Chrome stability
    environment:
      - APP_ENV=production
      - DISPLAY=:99
    env_file:
      - .env
    networks:
      - streaming_network
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'

  redis:
    image: redis:7-alpine
    container_name: streaming_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - streaming_network

  nginx:
    image: nginx:alpine
    container_name: streaming_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - ./static:/var/www/static
    depends_on:
      - youtube-streaming-bot
    networks:
      - streaming_network

networks:
  streaming_network:
    driver: bridge

volumes:
  redis_data:
    driver: local
