# YouTube Streaming Bot Configuration

# Dashboard Settings
dashboard:
  host: "0.0.0.0"
  port: 5000
  debug: false
  secret_key: "youtube-streaming-bot-secret-key-change-in-production"

# YouTube API Settings
youtube:
  client_secrets_file: "config/client_secrets.json"
  api_key: ""
  client_id: ""
  client_secret: ""
  timeout: 30

# Streaming Settings (Direct FFmpeg - No OBS Required)
streaming:
  rtmp_url: "rtmp://a.rtmp.youtube.com/live2"
  stream_key: ""
  resolution: "1280x720"
  fps: 30
  bitrate: 2500
  input_source: "testsrc"  # Options: testsrc, webcam, screen, /dev/video0
  audio_source: "default"  # Audio input device
  encoding_preset: "fast"  # FFmpeg preset: ultrafast, superfast, veryfast, faster, fast, medium, slow
  buffer_size: 5000  # Buffer size in KB
  keyframe_interval: 2  # Keyframe interval in seconds
  auto_restart: false

# Bot Settings
bot:
  # Comment Bot
  comments:
    enabled: false
    interval: 30  # seconds between comments
    max_comments: 50
    random_delay: 10
    accounts_file: "config/accounts.json"
    comments_file: "config/comments.json"
    
  # Viewer Bot
  viewers:
    enabled: false
    max_instances: 10
    session_duration: 15  # minutes
    use_proxies: false

# Scheduler Settings
scheduler:
  enabled: false
  timezone: "UTC"
